/**
 * Builds the docs/ directory:
 *   1. Runs `forge doc` to regenerate contract API reference
 *   2. Auto-generates: addresses, SDK API reference, events
 *   3. Validates that all hand-written pages exist
 *
 * Usage: bun run script/build-docs.ts
 */
import { execSync } from "node:child_process";
import { cp, rm, access, readFile, writeFile, readdir, mkdir } from "node:fs/promises";
import { join } from "node:path";
import { CONTRACTS, LABELS, CHAINS, ADDRESS_LABELS } from "./contracts";
import { addresses } from "../sdk/src/addresses";

const ROOT = join(import.meta.dirname, "..");
const OUT_DIR = join(ROOT, "out");
const DOCS_DIR = join(ROOT, "docs");
const CONTRACTS_DIR = join(DOCS_DIR, "contracts");
const FORGE_DOC_TMP = join(ROOT, ".forge-doc-tmp");

// Hand-written pages that must exist (relative to docs/)
const REQUIRED_PAGES = [
  "README.md",
  "FAQ.md",
  "protocol/overview.md",
  "protocol/governance.md",
  "protocol/staking.md",
  "protocol/slashing.md",
  "protocol/treasury.md",
  "sdk/getting-started.md",
  "sdk/examples.md",
  "integration/ui-spec.md",
  "integration/deployment.md",
];

// Auto-generated pages
const GENERATED_PAGES = [
  "operations/addresses.md",
  "sdk/api-reference.md",
  "integration/events.md",
];

type AbiEntry = {
  type: string;
  name?: string;
  inputs?: { name: string; type: string; indexed?: boolean }[];
};

function run(cmd: string) {
  console.log(`  $ ${cmd}`);
  execSync(cmd, { cwd: ROOT, stdio: "inherit" });
}

async function exists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

async function countFiles(dir: string, ext: string): Promise<number> {
  let count = 0;
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      count += await countFiles(full, ext);
    } else if (entry.name.endsWith(ext)) {
      count++;
    }
  }
  return count;
}

async function loadAbi(name: string): Promise<AbiEntry[]> {
  const artifactPath = CONTRACTS[name];
  const raw = await readFile(join(OUT_DIR, artifactPath), "utf-8");
  return JSON.parse(raw).abi;
}

// ---------------------------------------------------------------------------
// Generator: operations/addresses.md
// ---------------------------------------------------------------------------
function generateAddresses(): string {
  const lines: string[] = [
    "<!-- AUTO-GENERATED by script/build-docs.ts — do not edit -->",
    "# Deployed Addresses",
    "",
  ];

  for (const [chainIdStr, addrs] of Object.entries(addresses)) {
    const chainId = Number(chainIdStr);
    const chain = CHAINS[chainId];
    if (!chain) continue;

    lines.push(`## ${chain.name} (Chain ID: ${chainId})`, "");
    lines.push("| Contract | Address |", "|---|---|");

    for (const [key, label] of Object.entries(ADDRESS_LABELS)) {
      const addr = (addrs as Record<string, string | undefined>)[key];
      if (addr) {
        lines.push(`| ${label} | [\`${addr}\`](${chain.explorer}/${addr}) |`);
      } else {
        lines.push(`| ${label} | — |`);
      }
    }
    lines.push("");
  }

  lines.push(
    "## Using in Code",
    "",
    "```ts",
    'import { addresses } from "@yellow-org/contracts";',
    "",
    "// Mainnet",
    'addresses[1].yellowToken',
    "",
    "// Sepolia",
    'addresses[11155111].faucet',
    "```",
    "",
  );

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Generator: sdk/api-reference.md
// ---------------------------------------------------------------------------
async function generateApiReference(): Promise<string> {
  const rows: string[] = [];

  for (const [name, artifactPath] of Object.entries(CONTRACTS)) {
    const abi = await loadAbi(name);
    const label = LABELS[name] ?? "";
    rows.push(`| \`${name}Abi\` | ${name} | ${abi.length} | ${label} |`);
  }

  return [
    "<!-- AUTO-GENERATED by script/build-docs.ts — do not edit -->",
    "# SDK — API Reference",
    "",
    "All exports from `@yellow-org/contracts`.",
    "",
    "## ABIs",
    "",
    "Each ABI is exported as a `const` array for full type inference with viem and wagmi.",
    "",
    "```ts",
    "import {",
    ...Object.keys(CONTRACTS).map((n) => `  ${n}Abi,`),
    '} from "@yellow-org/contracts";',
    "```",
    "",
    "| Export | Contract | ABI Entries | Description |",
    "|---|---|---|---|",
    ...rows,
    "",
    "### Interface ABIs",
    "",
    "Use `ILockAbi` to write generic code that works with both NodeRegistry and AppRegistry:",
    "",
    "```ts",
    'import { ILockAbi } from "@yellow-org/contracts";',
    "",
    "// Works with either registry",
    "const balance = await client.readContract({",
    "  address: registryAddress,",
    "  abi: ILockAbi,",
    '  functionName: "balanceOf",',
    "  args: [userAddress],",
    "});",
    "```",
    "",
    "## Addresses",
    "",
    "```ts",
    'import { addresses, type ContractAddresses } from "@yellow-org/contracts";',
    "```",
    "",
    "### `addresses`",
    "",
    "`Record<number, Partial<ContractAddresses>>` — deployed addresses keyed by chain ID.",
    "",
    "```ts",
    "addresses[1]         // Ethereum Mainnet",
    "addresses[11155111]  // Sepolia",
    "```",
    "",
    "### `ContractAddresses` type",
    "",
    "```ts",
    "type ContractAddresses = {",
    '  yellowToken: `0x${string}`;',
    '  nodeRegistry: `0x${string}`;',
    '  appRegistry: `0x${string}`;',
    '  governor: `0x${string}`;',
    '  timelock: `0x${string}`;',
    '  treasury: `0x${string}`;',
    '  faucet?: `0x${string}`;  // testnet only',
    "};",
    "```",
    "",
    "### Current Addresses",
    "",
    "See [Deployed Addresses](../operations/addresses.md) for the full list.",
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Generator: integration/events.md
// ---------------------------------------------------------------------------
async function generateEvents(): Promise<string> {
  // Contracts to extract events from, grouped by section
  const sections: { title: string; description: string; contracts: string[] }[] = [
    {
      title: "Staking Events",
      description: "Emitted by both NodeRegistry and AppRegistry (inherited from Locker).",
      contracts: ["ILock"],
    },
    {
      title: "Voting Events",
      description: "Emitted by NodeRegistry only (inherited from OZ Votes).",
      contracts: ["NodeRegistry"],
    },
    {
      title: "Slashing Events",
      description: "Emitted by AppRegistry only.",
      contracts: ["AppRegistry"],
    },
    {
      title: "Governance Events",
      description: "Emitted by YellowGovernor.",
      contracts: ["YellowGovernor"],
    },
    {
      title: "Treasury Events",
      description: "Emitted by Treasury.",
      contracts: ["Treasury"],
    },
    {
      title: "Faucet Events",
      description: "Emitted by Faucet (Sepolia only).",
      contracts: ["Faucet"],
    },
  ];

  // Track already-listed events to avoid duplicates across sections
  const seen = new Set<string>();
  // ILock events are shared — exclude them from contract-specific sections
  const iLockAbi = await loadAbi("ILock");
  const iLockEvents = new Set(
    iLockAbi.filter((e) => e.type === "event").map((e) => e.name!)
  );
  // ISlash events
  const iSlashAbi = await loadAbi("ISlash");
  const iSlashEvents = new Set(
    iSlashAbi.filter((e) => e.type === "event").map((e) => e.name!)
  );

  const lines: string[] = [
    "<!-- AUTO-GENERATED by script/build-docs.ts — do not edit -->",
    "# Events",
    "",
    "Contract events for real-time UI subscriptions. Use `watchContractEvent` (viem) or `contract.on` (ethers) to listen.",
    "",
  ];

  for (const section of sections) {
    lines.push(`## ${section.title}`, "", section.description, "");
    lines.push("| Event | Parameters | Indexed |", "|---|---|---|");

    for (const contractName of section.contracts) {
      const abi = await loadAbi(contractName);
      const events = abi.filter((e) => e.type === "event");

      for (const event of events) {
        const name = event.name!;

        // Skip ILock events when listing contract-specific sections
        if (contractName !== "ILock" && iLockEvents.has(name)) continue;
        // Skip ISlash events when listing AppRegistry (they show under ISlash if we had a section)
        if (contractName === "AppRegistry" && iSlashEvents.has(name)) continue;
        // Skip duplicates
        if (seen.has(name)) continue;
        seen.add(name);

        const params = (event.inputs ?? [])
          .map((i) => `\`${i.name}\` (${i.type})`)
          .join(", ");
        const indexed = (event.inputs ?? [])
          .filter((i) => i.indexed)
          .map((i) => `\`${i.name}\``)
          .join(", ") || "—";

        lines.push(`| \`${name}\` | ${params} | ${indexed} |`);
      }
    }

    lines.push("");
  }

  // Add usage example
  lines.push(
    "## Subscribing with the SDK",
    "",
    "```ts",
    'import { NodeRegistryAbi, YellowGovernorAbi, addresses } from "@yellow-org/contracts";',
    "",
    "// Watch locks",
    "publicClient.watchContractEvent({",
    "  address: addresses[1].nodeRegistry!,",
    "  abi: NodeRegistryAbi,",
    '  eventName: "Locked",',
    "  onLogs: (logs) => {",
    "    for (const log of logs) {",
    "      console.log(`${log.args.user} locked ${log.args.deposited}`);",
    "    }",
    "  },",
    "});",
    "",
    "// Watch proposals",
    "publicClient.watchContractEvent({",
    "  address: addresses[1].governor!,",
    "  abi: YellowGovernorAbi,",
    '  eventName: "ProposalCreated",',
    "  onLogs: (logs) => {",
    "    for (const log of logs) {",
    "      console.log(`New proposal: ${log.args.proposalId}`);",
    "    }",
    "  },",
    "});",
    "```",
    "",
  );

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
async function main() {
  console.log("Building docs...\n");

  // 1. Forge doc
  console.log("[1/5] Generating contract docs with forge doc");
  await rm(FORGE_DOC_TMP, { recursive: true, force: true });
  run(`forge doc --out "${FORGE_DOC_TMP}"`);

  // 2. Replace docs/contracts/
  console.log("\n[2/5] Updating docs/contracts/");
  const srcDir = join(FORGE_DOC_TMP, "src", "src");
  if (!(await exists(srcDir))) {
    console.error(`Expected forge doc output at ${srcDir}`);
    process.exit(1);
  }
  await rm(CONTRACTS_DIR, { recursive: true, force: true });
  await cp(srcDir, CONTRACTS_DIR, { recursive: true });
  await rm(FORGE_DOC_TMP, { recursive: true, force: true });
  const contractPages = await countFiles(CONTRACTS_DIR, ".md");
  console.log(`  ${contractPages} contract pages generated`);

  // 3. Auto-generate pages
  console.log("\n[3/5] Auto-generating pages");

  await mkdir(join(DOCS_DIR, "operations"), { recursive: true });
  await mkdir(join(DOCS_DIR, "sdk"), { recursive: true });
  await mkdir(join(DOCS_DIR, "integration"), { recursive: true });

  const addressesMd = generateAddresses();
  await writeFile(join(DOCS_DIR, "operations/addresses.md"), addressesMd);
  console.log("  generated  operations/addresses.md");

  const apiRefMd = await generateApiReference();
  await writeFile(join(DOCS_DIR, "sdk/api-reference.md"), apiRefMd);
  console.log("  generated  sdk/api-reference.md");

  const eventsMd = await generateEvents();
  await writeFile(join(DOCS_DIR, "integration/events.md"), eventsMd);
  console.log("  generated  integration/events.md");

  // 4. Validate hand-written pages
  console.log("\n[4/5] Validating hand-written pages");
  const missing: string[] = [];
  for (const page of REQUIRED_PAGES) {
    const full = join(DOCS_DIR, page);
    if (!(await exists(full))) {
      missing.push(page);
    } else {
      console.log(`  ok  ${page}`);
    }
  }

  if (missing.length > 0) {
    console.error(`\nMissing ${missing.length} required page(s):`);
    for (const m of missing) {
      console.error(`  ✗  ${m}`);
    }
    process.exit(1);
  }

  // 5. Summary
  const totalPages = await countFiles(DOCS_DIR, ".md");
  console.log(`\n[5/5] Done`);
  console.log(`  ${contractPages} contract API pages (forge doc)`);
  console.log(`  ${GENERATED_PAGES.length} auto-generated pages`);
  console.log(`  ${REQUIRED_PAGES.length} hand-written pages (validated)`);
  console.log(`  ${totalPages} total markdown files in docs/`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
